services:
  node:
    image: "node:lts"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - /inbound
      - /outbound
      - /processed
    command: "npm start"

 